Base CRUD
click-nd-rest/generation-service pull request #1
Opened 2022-11-29 14:30 UTC by perf3ctstyle

2022-11-29 17:40 UTC, straightth requested changes

2022-11-29 17:40 UTC, straightth commented on base-crud-app/build.gradle
> +    implementation 'org.gitlab4j:gitlab4j-api:5.0.1'
Давай в новом сервисе подчистим лишние зависимости вроде этой, чтобы он был более легковесным

2022-11-29 17:40 UTC, straightth commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/BaseCrudApplication.java
> +	public static void main(String[] args) {
8 пробелов вместо 4

2022-11-29 17:40 UTC, straightth commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/exception/handlers/GenericExceptionHandler.java
> +public class GenericExceptionHandler extends ResponseEntityExceptionHandler {
Необязательное наследование

2022-11-29 17:40 UTC, straightth commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/domain/Resource.java
> +@NoArgsConstructor
Можно заменить аннотацией `@Data`

2022-11-29 17:40 UTC, straightth commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/repository/impl/MongoResourceRepositoryImpl.java
> +public class MongoResourceRepositoryImpl implements ResourceRepository {
Давай заменим на MongoRepository, чтобы не поддерживать свою реализацию репозитория: https://www.baeldung.com/spring-data-mongodb-tutorial

2022-11-29 17:40 UTC, straightth commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/exception/impl/ExceptionResponse.java
> +@Getter
Можно заменить на  `@Value`

2022-11-29 17:40 UTC, straightth commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/controller/ResourceController.java
> +        return service.findByName(name);
Давай делигировать вызов сразу репозиторию, чтобы выиграть в простоте шаблонизации

2022-11-29 17:40 UTC, straightth commented on base-crud-app/src/test/java/com/github/click/nd/rest/repository/ResourceRepositoryTest.java
> +        assertNull(actualBeforeSaving);
Не нужно тестировать репозиторий на предмет того, что он не сохранил в себя какой-то мусор сам

2022-11-29 17:40 UTC, straightth commented on base-crud-app/src/test/java/com/github/click/nd/rest/repository/ResourceRepositoryTest.java
> +        repository.deleteAll();
Предлагаю добиться изоляции тестов аннотацией `@Transactional` на класс: это более акууратно и правильно

2022-11-29 17:40 UTC, straightth commented on base-crud-app/src/test/java/com/github/click/nd/rest/repository/ResourceRepositoryTest.java
> +        Resource expected = new Resource("name");
Тестовые данные (в данном случае expected) уместно хардкодить внутри метода assert: так тесты будут более лаконичными
Чтобы сделать их ещё чище, можно делать методы вида `className(Object only, Object required, Object args)` и использовать var

2022-11-29 17:40 UTC, straightth commented on base-crud-app/src/test/java/com/github/click/nd/rest/repository/ResourceRepositoryTest.java
> +        assertNull(actualBeforeSaving);
AssertJ гораздо более мощный и удобный, чем обычные ассёрты

2022-11-29 17:40 UTC, straightth commented on base-crud-app/src/test/java/com/github/click/nd/rest/repository/ResourceRepositoryTest.java
> +public class ResourceRepositoryTest {
Под интеграционными тестами я подразумевал MockMvc: тут мой факап, у нас юнитами считаются тесты с in-memory Постгрёй, с точки зрения терминологии это интеграционный тест
После перехода на MongoRepository стоит отказаться от теста репозитория, чтобы не тестировать Спринг

Если будет время, то подёргай ручки в MockMvc, но можем вмёрджить и так, потому что у нас почти не будет собственной логики и мы вполне можем понадеяться на Спринг

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/build.gradle
> +    implementation 'org.gitlab4j:gitlab4j-api:5.0.1'
Удалил эту зависимость

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/BaseCrudApplication.java
> +	public static void main(String[] args) {
Здесь очень бы пригодился инструмент, могущий это форматировать автоматически.
Без него выслеживание таких недочетов и их форматирование, боюсь, может отнять очень много времени.
Решил оставить, как есть

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/controller/ResourceController.java
> +        return service.findByName(name);
Слой сервиса полностью удален, вызовы в контроллере делегируются напрямую в репозиторий

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/domain/Resource.java
> +@NoArgsConstructor
Все аннотации заменены на одну аннотацию `@Data`

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/exception/handlers/GenericExceptionHandler.java
> +public class GenericExceptionHandler extends ResponseEntityExceptionHandler {
Наследование удалено

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/exception/impl/ExceptionResponse.java
> +@Getter
Хотя `@Value` действительно включает в себя эти две аннотации, она добавляет еще и переопределенные `toString(), equals() и hashCode()`, которые не используются с объектами этого класса в этом модуле. Предлагаю следовать YAGNI и оставить все, как есть :)

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/repository/impl/MongoResourceRepositoryImpl.java
> +public class MongoResourceRepositoryImpl implements ResourceRepository {
Этот класс удален, а ResourceRepository теперь наследуется от MongoRepository

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/src/test/java/com/github/click/nd/rest/repository/ResourceRepositoryTest.java
> +public class ResourceRepositoryTest {
Удалил все тесты репозитория
Напишу тесты на контроллер, если смогу

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/src/test/java/com/github/click/nd/rest/repository/ResourceRepositoryTest.java
> +        repository.deleteAll();
Тесты удалены, но замечание учтено :)
@Transactional на каком классе?

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/src/test/java/com/github/click/nd/rest/repository/ResourceRepositoryTest.java
> +        Resource expected = new Resource("name");
Тесты удалены, но замечание учтено :)

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/src/test/java/com/github/click/nd/rest/repository/ResourceRepositoryTest.java
> +        assertNull(actualBeforeSaving);
Тесты удалены, но замечание учтено :)

2022-11-30 10:40 UTC, perf3ctstyle commented on base-crud-app/src/test/java/com/github/click/nd/rest/repository/ResourceRepositoryTest.java
> +        assertNull(actualBeforeSaving);
И снова удалены, но замечание учтено :)

2022-11-30 10:58 UTC, straightth commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/BaseCrudApplication.java
> +	public static void main(String[] args) {
На это даже есть задачка: https://app.clickup.com/t/2vyd0cr
При внесении таких штук их стоит исправлять, если они обнаружились

2022-11-30 11:03 UTC, straightth commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/exception/impl/ExceptionResponse.java
> +@Getter
Мне кажется странным избегать корректного переопределения методов с помощью `@Value`
Суть YAGNI же не в том, чтобы избегать полезных изменений в коде, а чтобы не писать код, который не понадобится
В этом случае мы ничего не теряем, а выигрываем в следующем:
- Код более консистентый и лаконичный: одна аннотация вместо зоопарка и не нужно бойлерплейтить private final
- Не придётся рефакторить код, когда понадобиться один из методов объекта: в случае с исключением это не произойдёт, но достаточно и предыдущего пункта

2022-11-30 11:05 UTC, straightth commented on base-crud-app/src/test/java/com/github/click/nd/rest/repository/ResourceRepositoryTest.java
> +        repository.deleteAll();
Мы делаем базовый класс для тестов с БД и кидаем `@Transactional` на него — так об изоляции вообще не приходится париться

2022-11-30 11:11 UTC, straightth requested changes

2022-11-30 11:11 UTC, straightth commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/exception/handlers/GenericExceptionHandler.java
> +        String message = (ex.getMessage() == null) ? ex.getClass().getName() : ex.getMessage();
У меня глаза горят красным от тернарников, они субъективно хуже читаются 🤯
Мне кажется, if читается проще

Ответственность за формирование ExceptionResponse в данном случае лежит на ExceptionResponse
Давай сделаем у него конструктор с сигнаторой вида (Exception, Code)

2022-11-30 11:11 UTC, straightth commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/configuration/ApplicationConfig.java
> +                .apis(RequestHandlerSelectors.basePackage("com.github.straight.flower.orangery"))
Здесь нужно подправить пакет контроллеров

2022-12-01 08:45 UTC, perf3ctstyle commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/configuration/ApplicationConfig.java
> +                .apis(RequestHandlerSelectors.basePackage("com.github.straight.flower.orangery"))
Поменял на пакет с контроллерами

2022-12-01 08:45 UTC, perf3ctstyle commented on base-crud-app/src/main/java/com/github/click/nd/rest/base/exception/handlers/GenericExceptionHandler.java
> +        String message = (ex.getMessage() == null) ? ex.getClass().getName() : ex.getMessage();
Возможно, это с непривычки. Чем чаще их(тернарники) встречаешь, тем проще к ним относишься :) У меня их довольно много на проекте.
В любом случае, в них отпала нужда, потому что
Заменил поле message на exception в ExceptionResponse и добавил конструктор ExceptionResponse(exception, status)

2022-12-01 08:55 UTC, straightth approved these changes

2022-12-01 08:55 UTC, merged