Unit tests
click-nd-rest/generation-service pull request #16
Opened 2022-12-15 10:09 UTC by perf3ctstyle

2022-12-17 14:35 UTC, straightth approved these changes

2022-12-17 14:35 UTC, straightth commented on generation-service/build.gradle
> -        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
А зачем ты убрал эксклюд?

2022-12-17 14:35 UTC, straightth commented on generation-service/src/test/java/com/github/click/nd/rest/generation/service/service/generation/ApiDefinitionServiceImplTest.java
> +    private final GitLabService gitLabService = mock(GitLabService.class);
Можно было замокать Гитлаб сервис — сделать реализацию GitLabService, из которой можно было вытаскивать состояние, и проверять её
Такой вариант более аккуратный и корректный с точки зрения тестирования

2022-12-17 14:35 UTC, straightth commented on generation-service/build.gradle
> -        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
Или верни его, или затри коммент сверху тоже

2022-12-17 14:36 UTC, straightth requested changes
Всё хорошо
Пофикси ворнинги и можно пушить

2022-12-17 20:43 UTC, perf3ctstyle commented on generation-service/build.gradle
> -        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
Изначально писал тесты через PowerMock, а там без этой библиотеки как раз было никуда.
Замечание принято - затер комментарий

2022-12-17 20:43 UTC, perf3ctstyle commented on generation-service/src/test/java/com/github/click/nd/rest/generation/service/service/generation/ApiDefinitionServiceImplTest.java
> +    private final GitLabService gitLabService = mock(GitLabService.class);
Честно говоря, не совсем понял, что именно ты имеешь здесь в виду
Это какая-то специальная реализация только для тестов?

2022-12-18 20:41 UTC, straightth approved these changes

2022-12-18 20:41 UTC, merged